# See options at https://github.com/coogie/oscailte
# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://github.com/Pyhive
baseurl: /pyhive.docs
title: pyhive-integration
subtitle: Python library for the Hive smart home platform
author: Pyhiveapi
simple_search: https://www.google.com/search
description: Documentation for pyhive-integration v2.0.0 — async and sync Python library for the Hive smart home platform.
theme: jekyll-theme-slate

permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
pre-commit:
  - check: FrontMatterVariableExists
    variables: ["description", "image"]
  - check: FrontMatterVariableIsNotDuplicate
    variables: ["description"]
  - check: FrontMatterVariableMeetsLengthRequirements
    variables: ["description", "title"]
  - check: NoDuplicateTags

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

plugins:
  - jekyll-time-to-read
  - jekyll-toc
  - jekyll-redirect-from
  - jekyll-relative-links
